#!/bin/bash

# Script to run legacy suppliers migration
# This is a one-time migration that copies all legacy_suppliers to the main Suppliers table

echo "🚀 Legacy Suppliers Migration"
echo "=============================="
echo ""
echo "This will:"
echo "  1. Fetch all records from legacy_suppliers table"
echo "  2. Check for duplicates in Suppliers table"
echo "  3. Create new Supplier records for non-duplicates"
echo ""
echo "IMPORTANT: You must be logged in as superadmin/founder to run this."
echo ""
echo "How to run:"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Log in as a superadmin or founder"
echo "  3. Open browser DevTools (F12)"
echo "  4. Go to Console tab"
echo "  5. Paste and run this command:"
echo ""
echo "     fetch('/api/migrate/legacy-suppliers', {method: 'POST'}).then(r => r.json()).then(console.log)"
echo ""
echo "Alternatively, if you're logged in, run this from terminal:"
echo ""
echo "  curl -X POST http://localhost:3000/api/migrate/legacy-suppliers \\"
echo "    -H 'Cookie: __session=YOUR_SESSION_COOKIE' \\"
echo "    | python3 -m json.tool"
echo ""
echo "The endpoint will return:"
echo "  - total: Total legacy suppliers found"
echo "  - migrated: Number of new suppliers created"
echo "  - skipped: Number of duplicates skipped"
echo "  - errors: Any errors encountered (if any)"
echo ""
